trigger:
- main  # or the branch you want to trigger from
 
pool: 
  name: my_win_pool
  # vmImage: 'ubuntu-latest'  # Select an Ubuntu VM for running tests
 
jobs:
- job: RunSeleniumTests
  displayName: 'Run Selenium Tests'
  steps:
 
    # Step 1: Install Python
    tasks:
      - name: Update system packages
        apt:
          name:
            - update
            - upgrade
          state: present

      - name: Install Python3
        apt:
          name: python3
          state: present

      - name: Install pip3
        apt:
          name: python3-pip
          state: present

      - name: Install pytest
        pip:
          name: pytest
          state: present 

      - name: Install pytest-html
        pip:
          name: pytest-html
          state: present 
    # - task: UsePythonVersion@0
    #   inputs:
    #     versionSpec: '3.10'
    #     addToPath: true

 
    # Step 2: Install dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
      displayName: 'Install dependencies'
 
    # Step 3: Set up WebDriver (Chromium)
    - script: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
      displayName: 'Install Chromium Browser'
 
    # Step 4: Set the environment variable for headless browser testing
    - script: |
        export DISPLAY=:99
      displayName: 'Set DISPLAY environment variable for headless testing'
 
    # Step 5: Run Selenium Tests using pytest
    - script: |
        pytest
      displayName: 'Run UI Selenium Tests'
 
    # Step 6: Upload Test Results (Optional: If you want to visualize test results in Azure DevOps)
    # - task: PublishTestResults@2
    #   inputs:
    #     testResultsFormat: 'JUnit'
    #     testResultsFiles: '**/test-*.xml'
    #     failTaskOnFailedTests: true
