trigger:
- main  # or the branch you want to trigger from
 
pool: 
  name: my_win_pool
  # vmImage: 'ubuntu-latest'  # Select an Ubuntu VM for running tests
 
jobs:
- job: RunSeleniumTests
  displayName: 'Run Selenium Tests'
  steps:
 
    # Step 1: Install Git
    - script: |
        sudo apt update
        sudo apt install git

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    # Step 2: Install dependencies
    - script: |
        sudo apt update
        sudo apt install git
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
      displayName: 'Install dependencies'
 
    # Step 3: Set up linux WebDriver (Chromium)
    - script: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
      displayName: 'Install Chromium Browser'
 
    # Step 4: Run Selenium Tests using pytest
    - script: |
        pytest --html=project/reports/report.html
      displayName: 'Run UI Selenium Tests'

    # Step 5: Download Test Artifacts 
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: project/reports
        artifactName: 'drop'
        publishLocation: 'Container'
        continueOnError: true

